"""
strategy_alignment_service.py — Conversational Strategy Alignment Enforcement
==============================================================================
Enforces strategy alignment on candidate replies generated by the AI sales runtime.
Prevents high-risk policy violations (e.g., selling after rejection, payment pressure
during browsing/stalled, resetting purchase commitment to discovery, untrusted commercial claims).
"""

import json
import logging
import re
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

from services.next_best_action_service import (
    ActionDecision,
    CtaPolicy,
    NextBestSalesAction,
    ProhibitedAction,
    QuestionPolicy,
    StrategyMode,
)
from services.sales_state_service import _fold_arabic, _matches_any, _strip_punctuation

log = logging.getLogger("adam.strategy_alignment")


@dataclass
class StrategyAlignmentResult:
    status: str  # "PASS", "REPAIRED", "SAFE_FALLBACK", "BLOCKED"
    final_answer: str
    violations: List[str] = field(default_factory=list)
    repaired: bool = False

    def to_dict(self) -> Dict[str, Any]:
        return {
            "status": self.status,
            "final_answer": self.final_answer,
            "violations": list(self.violations),
            "repaired": self.repaired,
        }


def _detect_rejection_violation(candidate_reply: str) -> bool:
    folded = _fold_arabic(candidate_reply)
    sales_tokens = [
        r"خصم",
        r"عرض",
        r"اشتري",
        r"اشتر",
        r"اطلب",
        r"تحويل",
        r"رقم\s+الدفع",
        r"رقم\s+الحساب",
        r"تواصل\s+معنا",
        r"فرصة",
        r"اشتراك",
        r"اشتري\s+دلوقتي",
        r"اشتري\s+الان",
    ]
    return any(re.search(_fold_arabic(pat), folded, re.I) for pat in sales_tokens)


def _detect_payment_pressure(candidate_reply: str) -> bool:
    folded = _fold_arabic(candidate_reply)
    pressure_tokens = [
        r"حول\s+دلوقتي",
        r"حول\s+الان",
        r"ادفع\s+حالا",
        r"ادفع\s+دلوقتي",
        r"ارسل\s+الفلوس",
        r"تحويل\s+البنك\s+فورا",
        r"ارسل\s+رقم\s+الدفع\s+الان",
        r"ابعت\s+الدفع",
        r"ابعتلي\s+الدفع",
        r"يلا\s+ابعت\s+الدفع",
        r"ابعت(لي)?\s+(ال)?دفع",
    ]
    return any(re.search(_fold_arabic(pat), folded, re.I) for pat in pressure_tokens)


def _detect_unnecessary_discovery_reset(candidate_reply: str) -> bool:
    folded = _fold_arabic(candidate_reply)
    reset_tokens = [
        r"خلينا\s+نبدأ\s+من\s+الأول",
        r"خلينا\s+نبدأ\s+من\s+الاول",
        r"نعرف\s+ميزانيتك\s+واحتياجاتك",
        r"عرفني\s+على\s+احتياجاتك\s+بالتفصيل",
        r"ميزانيتك\s+كام\s+واحتياجك",
    ]
    return any(re.search(_fold_arabic(pat), folded, re.I) for pat in reset_tokens)


def _detect_post_sale_sales_push(candidate_reply: str) -> bool:
    folded = _fold_arabic(candidate_reply)
    push_tokens = [
        r"اشتري\s+منتج\s+تاني",
        r"اشتري\s+منتج\s+ثاني",
        r"اشتر\s+منتج",
        r"بالمناسبة\s+اشتر",
        r"عندنا\s+عرض\s+جديد\s+على",
    ]
    return any(re.search(_fold_arabic(pat), folded, re.I) for pat in push_tokens)


def _detect_untrusted_discount(candidate_reply: str, company_knowledge: Optional[Dict[str, Any]] = None) -> bool:
    # Look for unauthorized discount percentages or claims
    m = re.search(r"خصم\s*(\d+|\d+\s*%|[٠-٩]+|[٠-٩]+\s*٪)", candidate_reply, re.I)
    if m:
        discount_str = m.group(0)
        # Check if company knowledge authorizes this exact discount
        knowledge_text = str(company_knowledge or "")
        if discount_str not in knowledge_text and "خصم" not in knowledge_text:
            return True
    return False


def _detect_untrusted_payment_destination(candidate_reply: str, company_knowledge: Optional[Dict[str, Any]] = None) -> bool:
    # Detect invented phone numbers/bank accounts passed as payment destinations
    numbers = re.findall(r"01[0125][0-9]{8}", candidate_reply)
    if numbers:
        knowledge_str = str(company_knowledge or "")
        for num in numbers:
            if num not in knowledge_str:
                return True
    return False


def _detect_fake_urgency_or_scarcity(candidate_reply: str, company_knowledge: Optional[Dict[str, Any]] = None) -> bool:
    folded = _fold_arabic(candidate_reply)
    urgency_scarcity_patterns = [
        r"خلال\s+ساعة",
        r"خلال\s+ساعه",
        r"قبل\s+انتهاء\s+العرض",
        r"اخر\s+قطعة",
        r"اخر\s+قطعه",
        r"آخر\s+قطعة",
        r"الكمية\s+نفدت",
        r"الفرصة\s+الأخيرة",
        r"فرصة\s+أخيرة",
        r"فرصه\s+اخيره",
    ]
    if any(re.search(_fold_arabic(pat), folded, re.I) for pat in urgency_scarcity_patterns):
        knowledge_str = _fold_arabic(str(company_knowledge or ""))
        if not any(token in knowledge_str for token in ["اخر قطعه", "خلال ساعه"]):
            return True
    return False


def _detect_explicit_question_ignored(user_input: str, candidate_reply: str) -> bool:
    user_folded = _fold_arabic(user_input)
    # Check if user asked explicit warranty or price question
    is_warranty_q = "ضمان" in user_folded or "warranty" in user_input.lower()
    is_price_q = any(k in user_folded for k in ["بكام", "سعر", "تكلفة", "price"])

    if is_warranty_q or is_price_q:
        reply_folded = _fold_arabic(candidate_reply)
        # If candidate only has payment demand without answering warranty/price
        if ("حول" in reply_folded or "ادفع" in reply_folded or "رقم الدفع" in reply_folded) and not any(
            k in reply_folded for k in ["ضمان", "سعر", "جنية", "جنيه", "شامل", "رصيد", "بكام", "تكلفة", "price", "warranty"]
        ):
            return True
    return False


def _detect_loan_pressure(candidate_reply: str) -> bool:
    folded = _fold_arabic(candidate_reply)
    loan_tokens = [
        r"استلف",
        r"خد\s+قرض",
        r"خذ\s+قرض",
        r"اقترض",
        r"borrow",
        r"take\s+a\s+loan",
    ]
    return any(re.search(_fold_arabic(pat), folded, re.I) for pat in loan_tokens)


def _detect_competitor_defamation_or_fake_social_proof(candidate_reply: str) -> bool:
    folded = _fold_arabic(candidate_reply)
    unethical_tokens = [
        r"المنافس\s+نصاب",
        r"المنافس\s+كذاب",
        r"المنافس\s+حرامي",
        r"عندنا\s+مليون\s+عميل",
        r"كل\s+الناس\s+بتثق\s+فينا",
        r"competitor\s+is\s+scam",
    ]
    return any(re.search(_fold_arabic(pat), folded, re.I) for pat in unethical_tokens)


def _detect_fake_memory_claim(candidate_reply: str, preference_memory: Optional[Any] = None) -> bool:
    if not candidate_reply:
        return False
    memory_claim_patterns = [
        r"فاكر\s+إنك\s+(?:قلتلي|ذكرت)",
        r"أنت\s+كنt\s+(?:قلتلي|بتفضل|تحب)\s*(?:قبل\s+كده)?",
        r"أنت\s+كنت\s+قلتلي",
        r"زي\s+ما\s+(?:أنت\s+)?دايمًا\s+بتحب",
        r"زي\s+ما\s+قلتلي\s+قبل\s+كده",
        r"بما\s+إنك\s+كنت\s+بتفضل",
        r"آخر\s+مرة\s+قلتلي",
        r"you\s+told\s+me\s+before",
        r"you\s+mentioned\s+before\s+that\s+you\s+prefer",
        r"as\s+you\s+always\s+prefer",
        r"last\s+time\s+you\s+said",
        r"i\s+remember\s+you\s+prefer",
        r"فاكر\s+إنك\s+prefer",
        r"remember\s+you\s+prefer",
    ]
    has_claim = any(re.search(pat, candidate_reply, re.IGNORECASE) for pat in memory_claim_patterns)
    if not has_claim:
        return False
    if not preference_memory or not hasattr(preference_memory, "active_preferences"):
        return True
    active_prefs = getattr(preference_memory, "active_preferences", [])
    if not active_prefs:
        return True
    return False


def _detect_fake_purchase_claim(candidate_reply: str, relationship_context: Optional[Any] = None) -> bool:
    if not candidate_reply:
        return False
    purchase_claim_patterns = [
        r"بما\s+إنك\s+اشتريت\s+.*?\s*قبل\s+كده",
        r"اشتريت\s+.*?\s*قبل\s+كده",
        r"اشتريت\s+مننا\s+قبل\s+كده",
        r"since\s+you\s+bought\s+.*?\s*from\s+us",
        r"since\s+you\s+bought\s+.*?\s*before",
        r"as\s+a\s+previous\s+buyer",
    ]
    has_claim = any(re.search(pat, candidate_reply, re.IGNORECASE) for pat in purchase_claim_patterns)
    if not has_claim:
        return False
    if not relationship_context or not hasattr(relationship_context, "continuity_status"):
        return True
    status = getattr(relationship_context, "continuity_status", "")
    status_val = status.value if hasattr(status, "value") else str(status)
    if status_val != "REPEAT_BUYER":
        return True
    return False


def enforce_strategy_alignment(
    user_input: str,
    candidate_reply: str,
    action_decision: ActionDecision,
    company_knowledge: Optional[Dict[str, Any]] = None,
    objection_snapshot: Optional[Any] = None,
    objection_policy: Optional[Any] = None,
    preference_memory: Optional[Any] = None,
    relationship_context: Optional[Any] = None,
) -> StrategyAlignmentResult:
    """
    Evaluates candidate_reply against action_decision and applies deterministic repair or fallback.
    Includes high-risk objection alignment safety checks.
    """
    reply = candidate_reply or ""
    violations: List[str] = []

    primary_action = action_decision.primary_action
    prohibited = set(action_decision.prohibited_actions or [])

    # Rule 1: Respect Rejection Violation
    if primary_action == NextBestSalesAction.RESPECT_REJECTION.value or ProhibitedAction.CONTINUE_SELLING_AFTER_REJECTION.value in prohibited:
        if _detect_rejection_violation(reply):
            violations.append("CONTINUE_SELLING_AFTER_REJECTION")
            repaired_text = "تمام يا فندم، شكراً لوقتك وأنا تحت أمرك في أي وقت إذا احتجت أي مساعدة مستقبلاً. 🙏"
            log.warning("[STRATEGY_ALIGNMENT] Repaired rejection violation: candidate attempted sales push after explicit rejection.")
            return StrategyAlignmentResult(
                status="REPAIRED",
                final_answer=repaired_text,
                violations=violations,
                repaired=True,
            )

    # Rule 2: Payment Pressure Violation
    if ProhibitedAction.PUSH_FOR_PAYMENT.value in prohibited or action_decision.cta_policy in {CtaPolicy.NONE.value, CtaPolicy.SOFT.value}:
        if _detect_payment_pressure(reply):
            violations.append("PUSH_FOR_PAYMENT")
            # Repair by removing aggressive payment pressure
            clean_reply = re.sub(
                r"(و?ابعت\s+الـ?دفع(\s+دلوقتي)?|و?حول\s+(دلوقتي|الان)|ادفع\s+(حالا|دلوقتي)|ارسل\s+الفلوس\s+فورا|تحويل\s+البنك\s+فورا)[\.!\؟\?]*",
                "",
                reply,
                flags=re.I,
            ).strip()
            if not clean_reply or len(clean_reply) < 5:
                clean_reply = "تمام يا فندم، أقدر أساعدك في أي استفسار عن منتجاتنا أو تفاصيل الخدمة. 👌"
            log.warning("[STRATEGY_ALIGNMENT] Repaired payment pressure violation.")
            return StrategyAlignmentResult(
                status="REPAIRED",
                final_answer=clean_reply,
                violations=violations,
                repaired=True,
            )

    # Rule 3: Premature Close during Comparison
    if primary_action == NextBestSalesAction.COMPARE_OPTIONS.value:
        if _detect_payment_pressure(reply) or ("اختر" in _fold_arabic(reply) and "حول" in _fold_arabic(reply)):
            violations.append("PREMATURE_CLOSE_DURING_COMPARISON")
            clean_reply = re.sub(
                r"(اختر\s+.*?\s+وابعت\s+الدفع|وحول\s+دلوقتي|ابعتلي\s+الدفع)[\.!\؟\?]*",
                "",
                reply,
                flags=re.I,
            ).strip()
            if not clean_reply:
                clean_reply = "أكيد، أقدر أقارن لك بين الاختيارات المتاحة عشان تختار الأنسب لك."
            log.warning("[STRATEGY_ALIGNMENT] Repaired premature close during comparison.")
            return StrategyAlignmentResult(
                status="REPAIRED",
                final_answer=clean_reply,
                violations=violations,
                repaired=True,
            )

    # Rule 4: Unnecessary Discovery Reset during Purchase Commitment
    if primary_action == NextBestSalesAction.FACILITATE_PURCHASE.value or ProhibitedAction.RESET_PURCHASE_TO_DISCOVERY.value in prohibited:
        if _detect_unnecessary_discovery_reset(reply):
            violations.append("RESET_PURCHASE_TO_DISCOVERY")
            repaired_text = "تمام يا فندم، أقدر أساعدك في إتمام الطلب والخطوة التالية مباشرة. ممكن تأكد لي التفاصيل المطلوبة للطلب؟"
            log.warning("[STRATEGY_ALIGNMENT] Repaired discovery reset during purchase execution.")
            return StrategyAlignmentResult(
                status="REPAIRED",
                final_answer=repaired_text,
                violations=violations,
                repaired=True,
            )

    # Rule 5: Sales Push during Post-Sale Support
    if primary_action == NextBestSalesAction.ROUTE_POST_SALE_SUPPORT.value or ProhibitedAction.FORCE_SALES_ON_SUPPORT.value in prohibited:
        if _detect_post_sale_sales_push(reply):
            violations.append("FORCE_SALES_ON_SUPPORT")
            repaired_text = "أهلاً بك، فاهم رسالتك بخصوص الدعم/الطلب، وجاري متابعة الأمر معك لحل المشكلة فوراً."
            log.warning("[STRATEGY_ALIGNMENT] Repaired sales push during post-sale support.")
            return StrategyAlignmentResult(
                status="REPAIRED",
                final_answer=repaired_text,
                violations=violations,
                repaired=True,
            )

    # Rule 6: Untrusted Discount
    if ProhibitedAction.OFFER_UNTRUSTED_DISCOUNT.value in prohibited or _detect_untrusted_discount(reply, company_knowledge):
        if _detect_untrusted_discount(reply, company_knowledge):
            violations.append("OFFER_UNTRUSTED_DISCOUNT")
            clean_reply = re.sub(r"(خصم\s*\d+\s*%?|خصم\s*[٠-٩]+\s*٪?)", "", reply, flags=re.I).strip()
            if not clean_reply:
                clean_reply = "تمام يا فندم، الأسعار المعتمدة موضحة في تفاصيل المنتجات، وأي خصومات متاحة سيتم إبلاغك بها."
            log.warning("[STRATEGY_ALIGNMENT] Repaired untrusted discount claim.")
            return StrategyAlignmentResult(
                status="REPAIRED",
                final_answer=clean_reply,
                violations=violations,
                repaired=True,
            )

    # Rule 7: Untrusted Payment Destination
    if ProhibitedAction.PROVIDE_UNTRUSTED_PAYMENT_DESTINATION.value in prohibited or _detect_untrusted_payment_destination(reply, company_knowledge):
        if _detect_untrusted_payment_destination(reply, company_knowledge):
            violations.append("PROVIDE_UNTRUSTED_PAYMENT_DESTINATION")
            repaired_text = "تمام يا فندم، يسعدنا مساعدتك في الشراء. سيقوم فريق المبيعات بتزوديك برقم الحساب أو رابط الدفع المعتمد."
            log.warning("[STRATEGY_ALIGNMENT] Blocked untrusted payment destination.")
            return StrategyAlignmentResult(
                status="REPAIRED",
                final_answer=repaired_text,
                violations=violations,
                repaired=True,
            )

    # Rule 8: Fake Urgency or Scarcity
    if ProhibitedAction.CREATE_URGENCY.value in prohibited or ProhibitedAction.CREATE_SCARCITY.value in prohibited:
        if _detect_fake_urgency_or_scarcity(reply, company_knowledge):
            violations.append("CREATE_URGENCY_OR_SCARCITY")
            clean_reply = re.sub(
                r"(خلال\s+ساعة|قبل\s+انتهاء\s+العرض\s+حالا|اخر\s+قطعة|آخر\s+قطعة|الكمية\s+نفدت|الفرصة\s+الأخيرة)[\.!\؟\?]*",
                "",
                reply,
                flags=re.I,
            ).strip()
            if not clean_reply:
                clean_reply = "تمام يا فندم، التفاصيل المتاحة موضحة بحسب المنتجات."
            log.warning("[STRATEGY_ALIGNMENT] Repaired fake urgency/scarcity claim.")
            return StrategyAlignmentResult(
                status="REPAIRED",
                final_answer=clean_reply,
                violations=violations,
                repaired=True,
            )

    # Rule 9: Evidence-bound price objection clarification. The selected
    # commercial move must resolve uncertainty, not stop at generic empathy.
    if getattr(action_decision, "next_move", "") == "ASK_BUDGET_OR_VALUE_CLARIFIER":
        reply_folded = _fold_arabic(reply)
        has_budget_or_value_question = any(token in reply_folded for token in ("ميزاني", "سقف", "قيمة", "مقابل", "budget", "value")) and ("؟" in reply or "?" in reply)
        if not has_budget_or_value_question:
            violations.append("PRICE_OBJECTION_MOVE_NOT_EXECUTED")
            repaired_text = "فاهم إن السعر مش مناسب بالشكل الحالي. عشان ما أفترضش السبب: عندك سقف ميزانية محدد، ولا تحب أوضح فرق القيمة المرتبط باحتياجك؟"
            log.warning("[STRATEGY_ALIGNMENT] Repaired generic price-objection reply into the selected clarifying move.")
            return StrategyAlignmentResult(
                status="REPAIRED",
                final_answer=repaired_text,
                violations=violations,
                repaired=True,
            )

    if getattr(action_decision, "selling_strategy", "") == "REANCHOR_VALUE":
        reply_folded = _fold_arabic(reply)
        has_need_link = any(token in reply_folded for token in ("شغل", "استخدام", "راحة", "دعم", "احتياج", "value", "need", "support"))
        if not has_need_link:
            violations.append("VALUE_REANCHOR_NOT_EXECUTED")
            repaired_text = "السعر مهم، وبما إن استخدامك للشغل هو السياق المعروف، خلّينا نقارن فقط فرق الراحة والدعم الموثقين مع ما تحتاجه فعلًا. لو عندك سقف ميزانية، اذكره لي عشان ما أرشحش لك خيارًا غير مناسب."
            log.warning("[STRATEGY_ALIGNMENT] Repaired generic price reply into the selected need-linked value move.")
            return StrategyAlignmentResult(
                status="REPAIRED",
                final_answer=repaired_text,
                violations=violations,
                repaired=True,
            )

    if getattr(action_decision, "selling_strategy", "") == "OFFER_TRUSTED_ALTERNATIVE":
        eligible = []
        for item in getattr(action_decision, "decision_evidence", []) or []:
            if item.get("type") == "eligible_trusted_products":
                eligible = item.get("value") or []
                break
        if eligible and not any(str(item.get("name", "")).casefold() in reply.casefold() for item in eligible):
            option = eligible[0]
            price = option.get("price")
            currency = f" {option.get('currency')}" if option.get("currency") else ""
            repaired_text = f"تمام، هاحترم سقف ميزانيتك. البديل الموثوق داخلها هو {option.get('name')} بسعر {price:g}{currency}. لو تحب، أوضح لك فقط الفرق المرتبط باستخدامك للشغل."
            violations.append("HARD_BUDGET_ALTERNATIVE_NOT_EXECUTED")
            log.warning("[STRATEGY_ALIGNMENT] Repaired hard-budget reply to the selected trusted alternative.")
            return StrategyAlignmentResult(
                status="REPAIRED",
                final_answer=repaired_text,
                violations=violations,
                repaired=True,
            )

    # Rule 10: Explicit Question Ignored
    if _detect_explicit_question_ignored(user_input, reply):
        violations.append("EXPLICIT_QUESTION_IGNORED")
        repaired_text = "أكيد، أقدر أساعدك وأجيب على سؤالك أولاً. ممكن توضح لي المنتج المطلوب لمعرفة كافة التفاصيل فوراً؟"
        log.warning("[STRATEGY_ALIGNMENT] Repaired ignored explicit customer question.")
        return StrategyAlignmentResult(
            status="REPAIRED",
            final_answer=repaired_text,
            violations=violations,
            repaired=True,
        )

    # Rule 10: Objection-Specific High Risk Alignments (Loan pressure & Competitor Defamation)
    if _detect_loan_pressure(reply):
        violations.append("LOAN_PRESSURE_PROHIBITED")
        has_explicit_budget_evidence = False
        if objection_snapshot:
            prim = getattr(objection_snapshot, "primary_objection", "")
            root = getattr(objection_snapshot, "root_cause_hypothesis", "")
            if prim == "BUDGET_CONSTRAINT" or root == "BUDGET_LIMIT":
                has_explicit_budget_evidence = True

        user_folded = _fold_arabic(user_input)
        if any(kw in user_folded for kw in ["ميزانيت", "معايا", "ميزانية", "أقصى", "حدود"]):
            has_explicit_budget_evidence = True

        if has_explicit_budget_evidence:
            repaired_text = "تمام يا فندم، بنحترم ميزانيتك وأقدر أعرض عليك بدائل تناسب الميزانية المحددة. 👌"
        else:
            repaired_text = "تمام يا فندم، بنحرص دايماً على توضيح قيمة وقدرات المنتج وتوفير خيارات متنوعة تناسبك. 👌"

        log.warning("[STRATEGY_ALIGNMENT] Repaired loan/borrowing pressure on budget objection.")
        return StrategyAlignmentResult(
            status="REPAIRED",
            final_answer=repaired_text,
            violations=violations,
            repaired=True,
        )

    if _detect_competitor_defamation_or_fake_social_proof(reply):
        violations.append("UNETHICAL_CLAIM_PROHIBITED")
        repaired_text = "يسعدنا توضيح تفاصيل شركتنا والضمانات المعتمدة بكل شفافية. 👌"
        log.warning("[STRATEGY_ALIGNMENT] Repaired unethical competitor defamation or fake social proof.")
        return StrategyAlignmentResult(
            status="REPAIRED",
            final_answer=repaired_text,
            violations=violations,
            repaired=True,
        )

    if _detect_fake_memory_claim(reply, preference_memory):
        violations.append("FAKE_MEMORY_CLAIM")
        repaired_text = "تحت أمرك يا فندم، إيه التفضيلات أو المواصفات اللي تحب نركز عليها؟ 👌"
        log.warning("[STRATEGY_ALIGNMENT] Repaired fake customer memory claim.")
        return StrategyAlignmentResult(
            status="REPAIRED",
            final_answer=repaired_text,
            violations=violations,
            repaired=True,
        )

    if _detect_fake_purchase_claim(reply, relationship_context):
        violations.append("FAKE_PURCHASE_CLAIM")
        repaired_text = "أهلاً بك يا فندم! تحت أمرك، حابب تعرف أكتُر عن إيه النهاردة؟ 👌"
        log.warning("[STRATEGY_ALIGNMENT] Repaired fake customer purchase claim.")
        return StrategyAlignmentResult(
            status="REPAIRED",
            final_answer=repaired_text,
            violations=violations,
            repaired=True,
        )

    return StrategyAlignmentResult(
        status="PASS",
        final_answer=reply,
        violations=[],
        repaired=False,
    )
