"""add_notifications_table

Revision ID: 00e0c3894a5f
Revises: 33337deb466f
Create Date: 2026-06-22 22:16:25.497632
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = "00e0c3894a5f"
down_revision: Union[str, None] = "33337deb466f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.String(length=64), nullable=False),
        sa.Column("lead_id", sa.Integer(), nullable=True),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("uuid", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["companies.company_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_notifications_company_id"), ["company_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_notifications_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_notifications_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_notifications_is_deleted"), ["is_deleted"], unique=False)
        batch_op.create_index(batch_op.f("ix_notifications_lead_id"), ["lead_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_notifications_uuid"), ["uuid"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notifications_uuid"))
        batch_op.drop_index(batch_op.f("ix_notifications_lead_id"))
        batch_op.drop_index(batch_op.f("ix_notifications_is_deleted"))
        batch_op.drop_index(batch_op.f("ix_notifications_id"))
        batch_op.drop_index(batch_op.f("ix_notifications_created_at"))
        batch_op.drop_index(batch_op.f("ix_notifications_company_id"))

    op.drop_table("notifications")
    # ### end Alembic commands ###
