"""add crm fields to leads

Revision ID: 01960c34b49b
Revises: 7c9ba56d9329
Create Date: 2026-06-16 19:19:14.755103
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = "01960c34b49b"
down_revision: Union[str, None] = "7c9ba56d9329"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leads", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_hot_deal", sa.Boolean(), server_default="0", nullable=False))
        batch_op.add_column(sa.Column("needs_human_intervention", sa.Boolean(), server_default="0", nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leads", schema=None) as batch_op:
        batch_op.drop_column("needs_human_intervention")
        batch_op.drop_column("is_hot_deal")

    # ### end Alembic commands ###
