"""add smart alerts columns

Revision ID: 19dedf08c9d1
Revises: fbe78468736b
Create Date: 2026-06-15 18:54:42.137995
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = "19dedf08c9d1"
down_revision: Union[str, None] = "001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    company_columns = {col["name"] for col in sa.inspect(op.get_bind()).get_columns("companies")}
    with op.batch_alter_table("companies", schema=None) as batch_op:
        if "is_alerts_enabled" not in company_columns:
            batch_op.add_column(sa.Column("is_alerts_enabled", sa.Boolean(), server_default=sa.text("0"), nullable=False))
        if "alert_whatsapp_number" not in company_columns:
            batch_op.add_column(sa.Column("alert_whatsapp_number", sa.String(length=20), nullable=True))
        if "daily_sales_target" not in company_columns:
            batch_op.add_column(sa.Column("daily_sales_target", sa.Integer(), server_default=sa.text("5"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("companies", schema=None) as batch_op:
        batch_op.drop_column("alert_whatsapp_number")
        batch_op.drop_column("is_alerts_enabled")

    # ### end Alembic commands ###
