"""add conversation_state to leads

Revision ID: 33337deb466f
Revises: f83ef5ef5077
Create Date: 2026-06-22 18:28:27.706392
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = "33337deb466f"
down_revision: Union[str, None] = "f83ef5ef5077"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _table_names() -> set[str]:
    return set(sa.inspect(op.get_bind()).get_table_names())


def _column_names(table_name: str) -> set[str]:
    return {col["name"] for col in sa.inspect(op.get_bind()).get_columns(table_name)}


def _create_index_if_missing(table_name: str, index_name: str, columns: list[str], unique: bool = False) -> None:
    existing_indexes = {idx["name"] for idx in sa.inspect(op.get_bind()).get_indexes(table_name)}
    if index_name not in existing_indexes:
        op.create_index(index_name, table_name, columns, unique=unique)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if "lead_memory" not in _table_names():
        op.create_table(
            "lead_memory",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("lead_id", sa.Integer(), nullable=True),
            sa.Column("customer_summary", sa.Text(), nullable=True),
            sa.Column("product_interest", sa.Text(), nullable=True),
            sa.Column("budget", sa.Text(), nullable=True),
            sa.Column("preferences", sa.Text(), nullable=True),
            sa.Column("purchase_history", sa.Text(), nullable=True),
            sa.Column("last_updated", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
            sa.Column("last_memory_rebuild_at", sa.DateTime(timezone=True), nullable=True),
            sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("id"),
        )

    lead_memory_columns = _column_names("lead_memory")
    with op.batch_alter_table("lead_memory", schema=None) as batch_op:
        if "uuid" not in lead_memory_columns:
            batch_op.add_column(sa.Column("uuid", sa.String(length=36), nullable=True))
        if "created_at" not in lead_memory_columns:
            batch_op.add_column(sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True))
        if "updated_at" not in lead_memory_columns:
            batch_op.add_column(sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True))
        if "is_deleted" not in lead_memory_columns:
            batch_op.add_column(sa.Column("is_deleted", sa.Boolean(), nullable=True))
        if "deleted_at" not in lead_memory_columns:
            batch_op.add_column(sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column("id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)

    _create_index_if_missing("lead_memory", "ix_lead_memory_created_at", ["created_at"])
    _create_index_if_missing("lead_memory", "ix_lead_memory_id", ["id"])
    _create_index_if_missing("lead_memory", "ix_lead_memory_is_deleted", ["is_deleted"])
    _create_index_if_missing("lead_memory", "ix_lead_memory_uuid", ["uuid"], unique=True)

    if "conversation_state" not in _column_names("leads"):
        with op.batch_alter_table("leads", schema=None) as batch_op:
            batch_op.add_column(sa.Column("conversation_state", sa.String(length=50), server_default="GREETING", nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leads", schema=None) as batch_op:
        batch_op.drop_column("conversation_state")

    with op.batch_alter_table("lead_memory", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lead_memory_uuid"))
        batch_op.drop_index(batch_op.f("ix_lead_memory_is_deleted"))
        batch_op.drop_index(batch_op.f("ix_lead_memory_id"))
        batch_op.drop_index(batch_op.f("ix_lead_memory_created_at"))
        batch_op.alter_column("id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
        batch_op.drop_column("deleted_at")
        batch_op.drop_column("is_deleted")
        batch_op.drop_column("updated_at")
        batch_op.drop_column("created_at")
        batch_op.drop_column("uuid")

    # ### end Alembic commands ###
