"""add_last_message_sender_to_leads

Revision ID: 581d7b7859b1
Revises: 00e0c3894a5f
Create Date: 2026-06-23 01:10:18.286957
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = "581d7b7859b1"
down_revision: Union[str, None] = "00e0c3894a5f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leads", schema=None) as batch_op:
        batch_op.add_column(sa.Column("last_message_sender", sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leads", schema=None) as batch_op:
        batch_op.drop_column("last_message_sender")

    # ### end Alembic commands ###
