"""add settings fields to company knowledge

Revision ID: 7c9ba56d9329
Revises: a2b497fd5c81
Create Date: 2026-06-16 02:34:59.333147
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = "7c9ba56d9329"
down_revision: Union[str, None] = "a2b497fd5c81"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    knowledge_columns = {col["name"] for col in sa.inspect(op.get_bind()).get_columns("company_knowledge")}
    with op.batch_alter_table("company_knowledge", schema=None) as batch_op:
        if "welcome_message" not in knowledge_columns:
            batch_op.add_column(sa.Column("welcome_message", sa.Text(), nullable=True))
        if "suggested_questions" not in knowledge_columns:
            batch_op.add_column(sa.Column("suggested_questions", sa.Text(), nullable=True))
        if "knowledge_base" not in knowledge_columns:
            batch_op.add_column(sa.Column("knowledge_base", sa.Text(), nullable=True))
        if "industry" not in knowledge_columns:
            batch_op.add_column(sa.Column("industry", sa.String(length=200), nullable=True))
        if "language" not in knowledge_columns:
            batch_op.add_column(sa.Column("language", sa.String(length=50), nullable=True))
        if "tone" not in knowledge_columns:
            batch_op.add_column(sa.Column("tone", sa.String(length=50), nullable=True))
        if "lead_collection" not in knowledge_columns:
            batch_op.add_column(sa.Column("lead_collection", sa.Boolean(), server_default="1", nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("company_knowledge", schema=None) as batch_op:
        batch_op.drop_column("lead_collection")
        batch_op.drop_column("tone")
        batch_op.drop_column("language")
        batch_op.drop_column("knowledge_base")
        batch_op.drop_column("suggested_questions")
        batch_op.drop_column("welcome_message")

    # ### end Alembic commands ###
