"""add customer temperature

Revision ID: a2b497fd5c81
Revises: 19dedf08c9d1
Create Date: 2026-06-15 21:31:25.300045
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = "a2b497fd5c81"
down_revision: Union[str, None] = "19dedf08c9d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leads", schema=None) as batch_op:
        batch_op.add_column(sa.Column("temperature", sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leads", schema=None) as batch_op:
        batch_op.drop_column("temperature")

    # ### end Alembic commands ###
