"""add lead_analytics

Revision ID: dd6a7529ebfc
Revises: 73326c00701f
Create Date: 2026-06-25 02:48:31.763958
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = "dd6a7529ebfc"
down_revision: Union[str, None] = "73326c00701f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    inspector = sa.inspect(op.get_bind())
    if "lead_analytics" not in inspector.get_table_names():
        op.create_table(
            "lead_analytics",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("lead_id", sa.Integer(), nullable=True),
            sa.Column("top_requested_products", sa.Text(), nullable=True),
            sa.Column("trending_topics", sa.Text(), nullable=True),
            sa.Column("business_opportunity", sa.Text(), nullable=True),
            sa.Column("last_analyzed_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
            sa.Column("uuid", sa.String(length=36), nullable=True),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
            sa.Column("is_deleted", sa.Boolean(), nullable=True),
            sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
            sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index("ix_lead_analytics_id", "lead_analytics", ["id"], unique=False)
        op.create_index("ix_lead_analytics_lead_id", "lead_analytics", ["lead_id"], unique=True)
        op.create_index("ix_lead_analytics_uuid", "lead_analytics", ["uuid"], unique=True)
        op.create_index("ix_lead_analytics_created_at", "lead_analytics", ["created_at"], unique=False)
        op.create_index("ix_lead_analytics_is_deleted", "lead_analytics", ["is_deleted"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
