"""Add delivery_status to Conversation

Revision ID: e1d929ea30b3
Revises: efeae303707f
Create Date: 2026-06-16 20:50:27.484094
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = "e1d929ea30b3"
down_revision: Union[str, None] = "efeae303707f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("delivery_status", sa.String(length=20), nullable=False, server_default="'delivered'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.drop_column("delivery_status")

    # ### end Alembic commands ###
