"""Add CRM Business Features

Revision ID: efeae303707f
Revises: 01960c34b49b
Create Date: 2026-06-16 20:28:51.111182
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = "efeae303707f"
down_revision: Union[str, None] = "01960c34b49b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leads", schema=None) as batch_op:
        batch_op.add_column(sa.Column("lead_score", sa.Integer(), nullable=False, server_default="0"))
        batch_op.add_column(sa.Column("status", sa.String(length=50), nullable=False, server_default="'عميل جديد'"))
        batch_op.add_column(sa.Column("ai_summary", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("last_message_preview", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leads", schema=None) as batch_op:
        batch_op.drop_column("last_message_preview")
        batch_op.drop_column("ai_summary")
        batch_op.drop_column("status")
        batch_op.drop_column("lead_score")

    # ### end Alembic commands ###
