"""Add Follow-Up Engine models

Revision ID: f83ef5ef5077
Revises: ff536d00c684
Create Date: 2026-06-20 18:23:21.106064
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = "f83ef5ef5077"
down_revision: Union[str, None] = "ff536d00c684"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _create_index_if_missing(table_name: str, index_name: str, columns: list[str], unique: bool = False) -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_indexes = {idx["name"] for idx in inspector.get_indexes(table_name)}
    if index_name not in existing_indexes:
        op.create_index(index_name, table_name, columns, unique=unique)


def _has_column(table_name: str, column_name: str) -> bool:
    return column_name in {col["name"] for col in sa.inspect(op.get_bind()).get_columns(table_name)}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = set(inspector.get_table_names())
    if "_alembic_tmp_leads" in existing_tables:
        op.drop_table("_alembic_tmp_leads")
    with op.batch_alter_table("leads", schema=None) as batch_op:
        if "is_paused" not in {col["name"] for col in inspector.get_columns("leads")}:
            batch_op.add_column(sa.Column("is_paused", sa.Boolean(), server_default=sa.text("0"), nullable=False))
        if "last_message" not in {col["name"] for col in inspector.get_columns("leads")}:
            batch_op.add_column(sa.Column("last_message", sa.Text(), nullable=True))
        if "first_contact_date" not in {col["name"] for col in inspector.get_columns("leads")}:
            batch_op.add_column(sa.Column("first_contact_date", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True))
        if "last_contact_date" not in {col["name"] for col in inspector.get_columns("leads")}:
            batch_op.add_column(sa.Column("last_contact_date", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True))
        if "summary" not in {col["name"] for col in inspector.get_columns("leads")}:
            batch_op.add_column(sa.Column("summary", sa.Text(), nullable=True))
        if "intent_score" not in {col["name"] for col in inspector.get_columns("leads")}:
            batch_op.add_column(sa.Column("intent_score", sa.Float(), nullable=True))
        if "opportunity_value" not in {col["name"] for col in inspector.get_columns("leads")}:
            batch_op.add_column(sa.Column("opportunity_value", sa.Float(), nullable=True))
        if "stage" not in {col["name"] for col in inspector.get_columns("leads")}:
            batch_op.add_column(sa.Column("stage", sa.String(length=100), server_default="Information Gathering", nullable=False))
        if "stage_updated_at" not in {col["name"] for col in inspector.get_columns("leads")}:
            batch_op.add_column(sa.Column("stage_updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True))
        if "is_test" not in {col["name"] for col in inspector.get_columns("leads")}:
            batch_op.add_column(sa.Column("is_test", sa.Boolean(), server_default=sa.text("0"), nullable=False))
        if "customer_health" not in {col["name"] for col in inspector.get_columns("leads")}:
            batch_op.add_column(sa.Column("customer_health", sa.String(length=50), nullable=True))
        if "tags" not in {col["name"] for col in inspector.get_columns("leads")}:
            batch_op.add_column(sa.Column("tags", sa.Text(), nullable=True))
        lead_columns = {col["name"] for col in sa.inspect(bind).get_columns("leads")}
        if "conversation_count" not in lead_columns:
            batch_op.add_column(sa.Column("conversation_count", sa.Integer(), server_default=sa.text("0"), nullable=False))
        else:
            batch_op.alter_column("conversation_count", existing_type=sa.INTEGER(), nullable=False, existing_server_default=sa.text("0"))

    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_messages_wa_message_id"))
        batch_op.create_index(batch_op.f("ix_messages_wa_message_id"), ["wa_message_id"], unique=True)

    # These runtime tables existed in the SQLAlchemy models but were missing from
    # the Alembic chain on fresh databases. Guarded creation keeps existing
    # development databases safe while making Alembic the canonical schema path.
    existing_tables = set(sa.inspect(bind).get_table_names())
    if "lead_memory" not in existing_tables:
        op.create_table(
            "lead_memory",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("lead_id", sa.Integer(), nullable=True),
            sa.Column("customer_summary", sa.Text(), nullable=True),
            sa.Column("product_interest", sa.Text(), nullable=True),
            sa.Column("budget", sa.Text(), nullable=True),
            sa.Column("preferences", sa.Text(), nullable=True),
            sa.Column("purchase_history", sa.Text(), nullable=True),
            sa.Column("last_updated", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
            sa.Column("last_memory_rebuild_at", sa.DateTime(timezone=True), nullable=True),
            sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("id"),
        )
        _create_index_if_missing("lead_memory", "ix_lead_memory_id", ["id"])
        _create_index_if_missing("lead_memory", "ix_lead_memory_lead_id", ["lead_id"], unique=True)
    else:
        if _has_column("lead_memory", "lead_id"):
            _create_index_if_missing("lead_memory", "ix_lead_memory_lead_id", ["lead_id"], unique=True)

    if "customer_notes" not in existing_tables:
        op.create_table(
            "customer_notes",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("lead_id", sa.Integer(), nullable=True),
            sa.Column("content", sa.Text(), nullable=False),
            sa.Column("author", sa.String(length=100), nullable=True),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
            sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("id"),
        )
        _create_index_if_missing("customer_notes", "ix_customer_notes_id", ["id"])
        _create_index_if_missing("customer_notes", "ix_customer_notes_lead_id", ["lead_id"])

    if "activity_logs" not in existing_tables:
        op.create_table(
            "activity_logs",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("lead_id", sa.Integer(), nullable=True),
            sa.Column("action_type", sa.String(length=100), nullable=False),
            sa.Column("event_type", sa.String(length=50), nullable=True),
            sa.Column("description", sa.Text(), nullable=True),
            sa.Column("metadata_payload", sa.Text(), nullable=True),
            sa.Column("timestamp", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
            sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("id"),
        )
        _create_index_if_missing("activity_logs", "ix_activity_logs_id", ["id"])
        _create_index_if_missing("activity_logs", "ix_activity_logs_lead_id", ["lead_id"])

    if "system_events" not in existing_tables:
        op.create_table(
            "system_events",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("company_id", sa.String(length=64), nullable=True),
            sa.Column("event_type", sa.String(length=100), nullable=False),
            sa.Column("entity_id", sa.String(length=128), nullable=True),
            sa.Column("payload", sa.Text(), nullable=False),
            sa.Column("processed", sa.Boolean(), nullable=True),
            sa.Column("uuid", sa.String(length=36), nullable=True),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
            sa.Column("is_deleted", sa.Boolean(), nullable=True),
            sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
            sa.ForeignKeyConstraint(["company_id"], ["companies.company_id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("id"),
        )
        _create_index_if_missing("system_events", "ix_system_events_id", ["id"])
        _create_index_if_missing("system_events", "ix_system_events_company_id", ["company_id"])
        _create_index_if_missing("system_events", "ix_system_events_event_type", ["event_type"])
        _create_index_if_missing("system_events", "ix_system_events_entity_id", ["entity_id"])
        _create_index_if_missing("system_events", "ix_system_events_processed", ["processed"])
        _create_index_if_missing("system_events", "ix_system_events_uuid", ["uuid"], unique=True)
        _create_index_if_missing("system_events", "ix_system_events_created_at", ["created_at"])
        _create_index_if_missing("system_events", "ix_system_events_is_deleted", ["is_deleted"])

    if "lead_events" not in existing_tables:
        op.create_table(
            "lead_events",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("lead_id", sa.Integer(), nullable=True),
            sa.Column("event_type", sa.String(length=100), nullable=False),
            sa.Column("description", sa.Text(), nullable=False),
            sa.Column("timestamp", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
            sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("id"),
        )
        _create_index_if_missing("lead_events", "ix_lead_events_id", ["id"])
        _create_index_if_missing("lead_events", "ix_lead_events_lead_id", ["lead_id"])

    if "lead_signals" not in existing_tables:
        op.create_table(
            "lead_signals",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("lead_id", sa.Integer(), nullable=True),
            sa.Column("signal_category", sa.String(length=100), nullable=False),
            sa.Column("score_modifier", sa.Integer(), nullable=False),
            sa.Column("reasoning", sa.Text(), nullable=False),
            sa.Column("timestamp", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
            sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("id"),
        )
        _create_index_if_missing("lead_signals", "ix_lead_signals_id", ["id"])
        _create_index_if_missing("lead_signals", "ix_lead_signals_lead_id", ["lead_id"])

    if "lead_intelligence_snapshots" not in existing_tables:
        op.create_table(
            "lead_intelligence_snapshots",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("lead_id", sa.Integer(), nullable=True),
            sa.Column("priority_score", sa.Integer(), nullable=False, server_default="0"),
            sa.Column("confidence_score", sa.Integer(), nullable=False, server_default="0"),
            sa.Column("lost_risk_score", sa.Integer(), nullable=False, server_default="0"),
            sa.Column("next_best_action", sa.Text(), nullable=True),
            sa.Column("action_reason", sa.Text(), nullable=True),
            sa.Column("why_summary", sa.Text(), nullable=True),
            sa.Column("why_here", sa.Text(), nullable=True),
            sa.Column("why_matter", sa.Text(), nullable=True),
            sa.Column("expected_outcome", sa.Text(), nullable=True),
            sa.Column("execution_sequence", sa.Text(), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
            sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("id"),
        )
        _create_index_if_missing("lead_intelligence_snapshots", "ix_lead_intelligence_snapshots_id", ["id"])
        _create_index_if_missing("lead_intelligence_snapshots", "ix_lead_intelligence_snapshots_lead_id", ["lead_id"], unique=True)

    if "follow_up_tasks" not in existing_tables:
        op.create_table(
            "follow_up_tasks",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("lead_id", sa.Integer(), nullable=True),
            sa.Column("task_level", sa.Integer(), nullable=False, server_default="1"),
            sa.Column("task_type", sa.String(length=100), nullable=False),
            sa.Column("status", sa.String(length=50), nullable=False, server_default="pending"),
            sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("suggested_message", sa.Text(), nullable=True),
            sa.Column("explanation", sa.Text(), nullable=True),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
            sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("id"),
        )
        _create_index_if_missing("follow_up_tasks", "ix_follow_up_tasks_id", ["id"])
        _create_index_if_missing("follow_up_tasks", "ix_follow_up_tasks_lead_id", ["lead_id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_messages_wa_message_id"))
        batch_op.create_index(batch_op.f("ix_messages_wa_message_id"), ["wa_message_id"], unique=False)

    with op.batch_alter_table("leads", schema=None) as batch_op:
        batch_op.alter_column("conversation_count", existing_type=sa.INTEGER(), nullable=True, existing_server_default=sa.text("0"))
        batch_op.drop_column("stage")
        batch_op.drop_column("opportunity_value")

    op.create_table(
        "_alembic_tmp_leads",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("company_id", sa.VARCHAR(length=64), nullable=True),
        sa.Column("name", sa.VARCHAR(length=200), nullable=False),
        sa.Column("phone", sa.VARCHAR(length=20), nullable=False),
        sa.Column("interest", sa.TEXT(), nullable=True),
        sa.Column("is_paused", sa.BOOLEAN(), nullable=False),
        sa.Column("uuid", sa.VARCHAR(length=36), nullable=True),
        sa.Column("created_at", sa.DATETIME(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.Column("updated_at", sa.DATETIME(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.Column("is_deleted", sa.BOOLEAN(), nullable=True),
        sa.Column("deleted_at", sa.DATETIME(), nullable=True),
        sa.Column("temperature", sa.VARCHAR(length=10), nullable=True),
        sa.Column("is_hot_deal", sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
        sa.Column("needs_human_intervention", sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
        sa.Column("lead_score", sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
        sa.Column("status", sa.VARCHAR(length=50), server_default=sa.text("'''عميل جديد'''"), nullable=False),
        sa.Column("ai_summary", sa.TEXT(), nullable=True),
        sa.Column("last_message_preview", sa.TEXT(), nullable=True),
        sa.Column("last_message", sa.TEXT(), nullable=True),
        sa.Column("conversation_count", sa.INTEGER(), server_default=sa.text("0"), nullable=False),
        sa.Column("first_contact_date", sa.DATETIME(), nullable=True),
        sa.Column("last_contact_date", sa.DATETIME(), nullable=True),
        sa.Column("opportunity_value", sa.FLOAT(), nullable=True),
        sa.Column("stage", sa.VARCHAR(length=100), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.company_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "phone", name=op.f("_company_phone_uc")),
    )
    # ### end Alembic commands ###
