"""Add Message model and MessageEvent

Revision ID: ff536d00c684
Revises: e1d929ea30b3
Create Date: 2026-06-20 02:07:33.074983
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = "ff536d00c684"
down_revision: Union[str, None] = "e1d929ea30b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table("conversations", schema=None) as batch_op:
            batch_op.drop_index(batch_op.f("ix_conv_company_user_ts"))
            batch_op.drop_index(batch_op.f("ix_conversations_company_id"))
            batch_op.drop_index(batch_op.f("ix_conversations_created_at"))
            batch_op.drop_index(batch_op.f("ix_conversations_id"))
            batch_op.drop_index(batch_op.f("ix_conversations_is_deleted"))
            batch_op.drop_index(batch_op.f("ix_conversations_user_id"))
            batch_op.drop_index(batch_op.f("ix_conversations_uuid"))
    except Exception:
        pass

    try:
        op.drop_table("conversations")
    except Exception:
        pass

    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("internal_message_id", sa.String(length=64), nullable=False),
        sa.Column("wa_message_id", sa.String(length=128), nullable=True),
        sa.Column("company_id", sa.String(length=64), nullable=True),
        sa.Column("user_id", sa.String(length=100), nullable=False),
        sa.Column("sender", sa.String(length=20), nullable=False),
        sa.Column("direction", sa.String(length=20), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("delivery_status", sa.String(length=20), server_default="pending", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.Column("uuid", sa.String(length=36), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["companies.company_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_messages_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_messages_internal_message_id"), ["internal_message_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_messages_wa_message_id"), ["wa_message_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_messages_user_id"), ["user_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_messages_company_id"), ["company_id"], unique=False)
        batch_op.create_index("ix_msg_company_user_ts", ["company_id", "user_id", "created_at"], unique=False)

    op.create_table(
        "message_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("message_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_message_events_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_message_events_message_id"), ["message_id"], unique=False)

    bind = op.get_bind()
    lead_columns = {col["name"] for col in sa.inspect(bind).get_columns("leads")}
    with op.batch_alter_table("leads", schema=None) as batch_op:
        if "conversation_count" not in lead_columns:
            batch_op.add_column(sa.Column("conversation_count", sa.Integer(), server_default=sa.text("0"), nullable=False))
        else:
            batch_op.alter_column("conversation_count", existing_type=sa.INTEGER(), nullable=False, existing_server_default=sa.text("0"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leads", schema=None) as batch_op:
        batch_op.alter_column("conversation_count", existing_type=sa.INTEGER(), nullable=True, existing_server_default=sa.text("0"))

    op.create_table(
        "conversations",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("company_id", sa.VARCHAR(length=64), nullable=True),
        sa.Column("user_id", sa.VARCHAR(length=100), nullable=False),
        sa.Column("sender", sa.VARCHAR(length=20), nullable=False),
        sa.Column("message", sa.TEXT(), nullable=False),
        sa.Column("uuid", sa.VARCHAR(length=36), nullable=True),
        sa.Column("created_at", sa.DATETIME(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.Column("updated_at", sa.DATETIME(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.Column("is_deleted", sa.BOOLEAN(), nullable=True),
        sa.Column("deleted_at", sa.DATETIME(), nullable=True),
        sa.Column("delivery_status", sa.VARCHAR(length=20), server_default=sa.text("'''delivered'''"), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.company_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_conversations_uuid"), ["uuid"], unique=1)
        batch_op.create_index(batch_op.f("ix_conversations_user_id"), ["user_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_conversations_is_deleted"), ["is_deleted"], unique=False)
        batch_op.create_index(batch_op.f("ix_conversations_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_conversations_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_conversations_company_id"), ["company_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_conv_company_user_ts"), ["company_id", "user_id", "created_at"], unique=False)

    # ### end Alembic commands ###
